# Generated by Django 5.2 on 2026-05-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emploi_du_temps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cours",
            options={
                "ordering": ["codeCours"],
                "verbose_name": "cours",
                "verbose_name_plural": "cours",
            },
        ),
    ]
