# Generated by Django 6.0.5 on 2026-05-29 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0002_alter_cours_volumehoraire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={},
        ),
        migrations.AlterField(
            model_name='cours',
            name='codeCours',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='code du cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='intitule',
            field=models.CharField(max_length=200, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='emploi_du_temps.option', verbose_name='option'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='volumeHoraire',
            field=models.PositiveIntegerField(verbose_name='volume horaire'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='emploi_du_temps.cours', verbose_name='cours'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='emploiDuTemps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='emploi_du_temps.emploidutemps', verbose_name='emploi du temps'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='creneauxEnseignes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='heureDebut',
            field=models.TimeField(verbose_name='heure de début'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='heureFin',
            field=models.TimeField(verbose_name='heure de fin'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='jour',
            field=models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=20, verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='emploi_du_temps.option', verbose_name='option'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='emploi_du_temps.salle', verbose_name='salle'),
        ),
    ]
