# Generated by Django 6.0.5 on 2026-05-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0003_alter_cours_options_alter_cours_codecours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['codeCours'], 'verbose_name': 'cours', 'verbose_name_plural': 'cours'},
        ),
    ]
