# Generated by Django 6.0.5 on 2026-05-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0004_alter_cours_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='volumeHoraire',
            field=models.CharField(blank=True, max_length=100, verbose_name='volume horaire'),
        ),
    ]
