# Generated by Django 5.2 on 2026-06-01 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emploi_du_temps", "0005_alter_cours_volumehoraire"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="etudiants",
                to="emploi_du_temps.option",
                verbose_name="option de l’étudiant",
            ),
        ),
    ]
